name: github CI

on:
    push:
        branches:
            - master
            - develop
    pull_request:

jobs:
    java_build:
        name: Java pipeline
        runs-on: ubuntu-latest
    
        steps:
            - name: Check out project
              uses: actions/checkout@v2
            
            - name: Set up JAVA
              uses: actions/setup-java@v1
              with:
                java-version: 11
                java-package: jdk
            
            - name: Compile and Checkstyle
              run: mvn package
